## Main Idea

Here we impliment the following idea: Given a 2D Hexagonal lattice, consider the (infinite) set of moves where every lattice point is involved in a pairwise (CCW or CW) exchange with one of its neighbors. We would like to see what combination of such moves, once repeated indefinately, results in the largest exponential rate of increase in the length of generic material lines.  Since there are an infinite number of possible ways to spatially arrange the switches in each move (due to the infinite lattice, infinite geometric configurations, and that each switch could be CW or CCW), we will try to answer a more constrained problem.  We can enumerate the number of unique moves for periodic moves of a given periodic domain (we consider a lattice on a torus).  

<img src="Pictures/HexLattice.jpg">

Here we consider the square lattice compatible with the torus that has six points (see below).  We use wrap-around conditions that make this a torus (here we are using the hexagon with identified opposite sides as the fundamental domain of the tours).  

<img src="Pictures/HexFD.jpg">

We will label the 9 edges as follows:

<img src="Pictures/HexGraphLabeled.jpg">

### Generators

We will refer to individual pair switches by the edge connecting the pair of points (there are 9), and a $\pm$ exponent to denote a counter clockwise (CCW $+$) or clockwise (CW $-$) exchange.  So, the 18 generators are: $\sigma^{\pm}_{i}$ for $i \in [1,9]$

Here we can execute three generators at a time.  An operator constitutes a set of generators that can act simultaneously.  There are 6 operator templates (compatible edge sets without the CW/CCW designation):

<img src="Pictures/OpTemplates2.jpg">

Each operator template has 3 edges, and each edge can be CCW or CW, so there are $6*2^3 = 48$ unique operators.

We will try to find the Braid word up to length 8 on these 48 operators which maximizes the topological entropy per operator.  We will sucessively check the low length braid words first.  We will try larger length braids on a smaller subset of possibilities. 

<img src="Pictures/TriangulationCoord.jpg">

## Triangulation Coordinates

We encode the way curves wind around the lattice points by specifying a triangulation.  In this case we need 9 more edges to create a triangulation (see above), for a total of 18 edges. Each edge weight counts the number of transverse intersections of the curves.  

For our initial curve, we will take the band $E = (0,1,0,0,0,1,1,0,1,1,1,0,1,0,1,0,1,1)$ - the band enclosing edge 1.  If the braid is pA, then this should stretch out exponentially.  The asymptotic weighted traintrack that results will not depend on this initial condition for a pA braid.

<img src="Pictures/TriangulationCoord.jpg">

## Symmetries

Using the above image, we can write down the coordinate transformations corresponding to a few useful symmetries - two types of rotations and a mirror inversion.  Here we consider the symmetries to act on the underlying triangulation (and we only consider symetries of the triangulation, even thought there are more for the hex lattice), and not the torus (as given by the Hexagonal fundamental domain).  The symmetries are: $R_1$ for a CCW rotation by $2\pi/3$ about the point with edges 1,2,7 emanating from it, $\overline{R}_1$ for a CW rotation by $2\pi/3$ about this point. $R_2$ for a CCW rotation by $2\pi/3$ about the center of the central hexigon, $\overline{R}_2$ for a CW rotation by $2\pi/3$ about this point.  And a mirror inversion about the horizontal line through edge 1 - $M$.  For $i \in [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]$, we give the action of the symmetry by the permutation $\pi(i)$. 


$R_1: \pi = (2,7,4,9,6,8,1,5,3,15,13,14,18,16,17,12,10,11)$  This has $R_1^3 = \mathbb{1}$ and $R_1^2 = \overline{R}_1$

$\overline{R}_1: \pi = (7,1,9,3,8,5,2,6,4,17,18,16,11,12,10,14,15,13)$

$R_2: \pi = (5,6,1,2,3,4,8,9,7,12,10,11,15,13,14,18,16,17)$  Again, This has $R_2^3 = \mathbb{1}$ and $R_2^2 = \overline{R}_2$

$\overline{R}_2: \pi = (3,4,5,6,1,2,9,7,8,11,12,10,14,15,13,17,18,16)$

$M: \pi = (1,7,5,8,3,9,2,4,6,18,17,16,15,14,13,12,11,10)$  Note that this will switch CCW and CW braid generators.  Also $M^2 = \mathbb{1}$

<img src="Pictures/TriangulationCoord.jpg">

## Symmetry Operators and Braid Generators

We will fully define the action of one generator on the coordinates ($S = \sigma^{+}_1$).  All other generators will be related to this one by conjugating with a set of symmetries.  The operators act via left action (right most operator acts first).  All inverses are given by replacing $S$ with $MSM$ in the formulas.


$\sigma^{+}_1 = S$   

$\sigma^{+}_2 = \overline{R}_1SR_1$

$\sigma^{+}_3 = R_2S\overline{R}_2$

$\sigma^{+}_4 = R_2\overline{R}_1SR_1\overline{R}_2$

$\sigma^{+}_5 = \overline{R}_2SR_2$

$\sigma^{+}_6 = \overline{R}_2\overline{R}_1SR_1R_2$

$\sigma^{+}_7 = R_1S\overline{R}_1$

$\sigma^{+}_8 = R_1\overline{R}_2SR_2\overline{R}_1$

$\sigma^{+}_9 = R_1R_2S\overline{R}_2\overline{R}_1$

<img src="Pictures/TriangulationCoord.jpg">

## Coordinate Update Rules

First for the update rule for $S$, which are constructed by breaking down the point interchange into a series of Whitehead moves and using our edge updating formula at each step.  Here is the formula for a Whitehead move (where E is the edge between the two triangles, A,B,C,D are the edges of the quadrilateral in cyclic order, and E' is the new edge after the flip):

$E' = \max(A+C,B+D) - E \equiv \Delta(A,B,C,D;E)$

Now we use this to construct the overall update rule for $S$.  Consider the following 2 figures.  The first shows the domain around edge 1 (the we will calculate $\sigma_1$) as we've shown it before, and rotated to correspond with the view in the flip graph.  The second shows the filp graph, or the sequence of edge flips and moves that build up $\sigma_1$.

<img src="Pictures/FlipDomain.jpg">

<img src="Pictures/FlipGraph2.jpg">


#### Rules for $S$

$(E^n = S E)$  :  $E^n_i = E^{*}_{\pi(i)}$, where $E^{*} = (E_1, E'_2, E_3, E_4, E_5, E'_6, E'_7, E_8, E''_9, E_{10}, E''_{11}, E_{12}, E'_{13}, E_{14}, E'_{15}, E_{16}, E''_{17}, E'_{18})$ and $\pi = (1, 15, 3, 4, 5, 10, 18, 8, 6, 2, 11, 12, 7, 14, 13, 16, 17, 9)$

$E'_{17} = \Delta(E_{18},E_{16},E_{5},E_{7};E_{17})$

$E'_{11} = \Delta(E_{2},E_{3},E_{12},E_{10};E_{11})$

$E'_{6} = \Delta(E_{1},E_{10},E_{14},E_{9};E_{6})$

$E'_{18} = \Delta(E_{1},E_{9},E'_{17},E_{7};E_{18})$

$E'_{9} = \Delta(E_{1},E'_{6},E'_{17},E'_{18};E_{9})$

$E'_{7} = \Delta(E_{1},E'_{18},E_{4},E_{13};E_{7})$

$E'_{13} = \Delta(E_{1},E'_{7},E_{14},E_{15};E_{13})$

$E'_{15} = \Delta(E_{1},E'_{13},E_{8},E_{2};E_{15})$

$E'_{2} = \Delta(E_{1},E'_{15},E'_{11},E_{10};E_{2})$

$E''_{9} = \Delta(E'_{18},E_{1},E'_{6},E'_{17};E'_{9})$

$E''_{17} = \Delta(E'_{18},E''_{9},E_{16},E_{5};E'_{17})$

$E''_{11} = \Delta(E'_{2},E'_{15},E_{3},E_{12};E'_{11})$

<img src="Pictures/FlipGraph2.jpg">

## Function Definitions

In [1]:
#Now we set up the functions, S, M, R, R-inv.  Each of them take in a numpy array of length 6 and output the same data type.
import numpy as np
import copy

#this is the fundamental function that updates the central edge in the Whitehead move
def Delta(A,B,C,D,E):
    return max(A+C,B+D) - E

#this updates the state of the triangulation vector for the CCW switch connectinging A and B along edge 2 (and outputs the new one).  Notice that the indexing is one less than in the notes (starts with 0)
def S_switch(WS):

    E16p = Delta(WS[17],WS[15],WS[4],WS[6],WS[16])

    E10p = Delta(WS[1],WS[2],WS[11],WS[9],WS[10])

    E5p = Delta(WS[0],WS[9],WS[13],WS[8],WS[5])

    E17p = Delta(WS[0],WS[8],E16p,WS[6],WS[17])

    E8p = Delta(WS[0],E5p,E16p,E17p,WS[8])

    E6p = Delta(WS[0],E17p,WS[3],WS[12],WS[6])

    E12p = Delta(WS[0],E6p,WS[13],WS[14],WS[12])

    E14p = Delta(WS[0],E12p,WS[7],WS[1],WS[14])

    E1p = Delta(WS[0],E14p,E10p,WS[9],WS[1])

    E8pp = Delta(E17p,WS[0],E5p,E16p,E8p)

    E16pp = Delta(E17p,E8pp,WS[15],WS[4],E16p)

    E10pp = Delta(E1p,E14p,WS[2],WS[11],E10p)

    return np.array([WS[0], E14p, WS[2], WS[3], WS[4], WS[9], E17p, WS[7], E5p, E1p, E10pp, WS[11], E6p, WS[13], E12p, WS[15], E16pp, E8pp])

#### Rules for $S$



#now for the Mirror flip about the horizontal axis
def M_flip(WS):
    return np.array([WS[0], WS[6], WS[4], WS[7], WS[2], WS[8], WS[1], WS[3], WS[5], WS[17], WS[16], WS[15], WS[14], WS[13], WS[12], WS[11], WS[10], WS[9]])

#CCW rotation
def R1_rot(WS):
    return np.array([WS[1], WS[6], WS[3], WS[8], WS[5], WS[7], WS[0], WS[4], WS[2], WS[14], WS[12], WS[13], WS[17], WS[15], WS[16], WS[11], WS[9], WS[10]])

#CW rotation
def R1Inv_rot(WS):
    return np.array([WS[6], WS[0], WS[8], WS[2], WS[7], WS[4], WS[1], WS[5], WS[3], WS[16], WS[17], WS[15], WS[10], WS[11], WS[9], WS[13], WS[14], WS[12]])

#CCW rotation
def R2_rot(WS):
    return np.array([WS[4], WS[5], WS[0], WS[1], WS[2], WS[3], WS[7], WS[8], WS[6], WS[11], WS[9], WS[10], WS[14], WS[12], WS[13], WS[17], WS[15], WS[16]])


#CW rotation
def R2Inv_rot(WS):
    return np.array([WS[2], WS[3], WS[4], WS[5], WS[0], WS[1], WS[8], WS[6], WS[7], WS[10], WS[11], WS[9], WS[13], WS[14], WS[12], WS[16], WS[17], WS[15]])

    
def SInv_switch(WS):
    return M_flip(S_switch(M_flip(WS)))

    
#now for the individual generators
def Sig1(WS,Positive = True):
    if Positive:
        return S_switch(WS)
    else:
        return SInv_switch(WS)
                      
def Sig2(WS,Positive = True):
    if Positive:
        return R1Inv_rot(S_switch(R1_rot(WS)))
    else:
        return R1Inv_rot(SInv_switch(R1_rot(WS)))
                                          
def Sig3(WS,Positive = True):
    if Positive:
        return R2_rot(S_switch(R2Inv_rot(WS)))
    else:
        return R2_rot(SInv_switch(R2Inv_rot(WS)))

def Sig4(WS,Positive = True):
    if Positive:
        return R2_rot(R1Inv_rot(S_switch(R1_rot(R2Inv_rot(WS)))))
    else:
        return R2_rot(R1Inv_rot(SInv_switch(R1_rot(R2Inv_rot(WS)))))

def Sig5(WS,Positive = True):
    if Positive:
        return R2Inv_rot(S_switch(R2_rot(WS)))
    else:
        return R2Inv_rot(SInv_switch(R2_rot(WS)))

def Sig6(WS,Positive = True):
    if Positive:
        return R2Inv_rot(R1Inv_rot(S_switch(R1_rot(R2_rot(WS)))))
    else:
        return R2Inv_rot(R1Inv_rot(SInv_switch(R1_rot(R2_rot(WS)))))

def Sig7(WS,Positive = True):
    if Positive:
        return R1_rot(S_switch(R1Inv_rot(WS)))
    else:
        return R1_rot(SInv_switch(R1Inv_rot(WS)))

def Sig8(WS,Positive = True):
    if Positive:
        return R1_rot(R2Inv_rot(S_switch(R2_rot(R1Inv_rot(WS)))))
    else:
        return R1_rot(R2Inv_rot(SInv_switch(R2_rot(R1Inv_rot(WS)))))

def Sig9(WS,Positive = True):
    if Positive:
        return R1_rot(R2_rot(S_switch(R2Inv_rot(R1Inv_rot(WS)))))
    else:
        return R1_rot(R2_rot(SInv_switch(R2Inv_rot(R1Inv_rot(WS)))))
      
def Generator(WS,n,Positive = True):
    switcher = {
        1: lambda WSin,Pos:Sig1(WSin,Pos),
        2: lambda WSin,Pos:Sig2(WSin,Pos),
        3: lambda WSin,Pos:Sig3(WSin,Pos),
        4: lambda WSin,Pos:Sig4(WSin,Pos),
        5: lambda WSin,Pos:Sig5(WSin,Pos),
        6: lambda WSin,Pos:Sig6(WSin,Pos),
        7: lambda WSin,Pos:Sig7(WSin,Pos),
        8: lambda WSin,Pos:Sig8(WSin,Pos),
        9: lambda WSin,Pos:Sig9(WSin,Pos)
    }
    return switcher.get(n)(WS,Positive)


Now we have all the functions defined that we need, and we can move on to lattice braid words acting on the triangluation coordinates

In [3]:
#First, we will wrap out definition of a lattice braid generator as a list [[i1,j1],[i2,j2],[i3,j3]], where j1/j2/j3 are True or False (CCW or CW), and i1/i2/i3 are the move subscripts (1-9)
def Lattice_Braid_Operator(WS, GenInfo):
    WSout = copy.copy(WS)
    for i in range(len(GenInfo)):
        WSout = Generator(WSout,GenInfo[i][0],GenInfo[i][1])
    return WSout
    

#now a braid word is a list of the Operator elements.  This function takes in such a list and outputs the triangulation coordinates after applying each of the generators (in index order: 0, 1, 2, ...)
def Lattice_Braid_Action(WS,LatticeBraid):
    WSout = copy.copy(WS)
    for i in range(len(LatticeBraid)):
        WSout = Lattice_Braid_Operator(WSout,LatticeBraid[i])
    return WSout

#We also need a function that gets the total weight of the triangulation coordinates (just sum of all weights)
def Weight_Total(WS):
    wtot = 0
    for i in range(len(WS)):
        wtot += WS[i]
    return wtot

#now let's generate 6 lists, each containing the operators corresponding to one of the 6 ways to group the points into 3 pairs (see image below)


def getGroup(gvals):
    grp = []
    TFvals = [True,True,True]
    for i in range(2):
        if i%2 == 0:
            TFvals[0] = True
        else:
            TFvals[0] = False
        for j in range(2):
            if j%2 == 0:
                TFvals[1] = True
            else:
                TFvals[1] = False
            for k in range(2):
                if k%2 == 0:
                    TFvals[2] = True
                else:
                    TFvals[2] = False
                gtemp = [[gvals[m],TFvals[m]] for m in range(3)]
                grp.append(gtemp)
    return grp

#G1: 1,3,5
g1vals = [1,3,5]
G1 = getGroup(g1vals)

#G2:
g2vals = [7,8,9]
G2 = getGroup(g2vals)

#G3:
g3vals = [2,4,6]
G3 = getGroup(g3vals)

#these three groups go together (they don't share any edges), so we package them together
Gset1 = G1+G2+G3

#G4:
g4vals = [2,5,9]
G4 = getGroup(g4vals)

#G5:
g5vals = [1,4,8]
G5 = getGroup(g5vals)

#G6:
g6vals = [3,6,7]
G6 = getGroup(g6vals)

#these three groups also go together (they don't share any edges), so we package them together too
Gset2 = G4+G5+G6

#now for the full combined set:
G = Gset1+Gset2

<img src="Pictures/OpTemplates2.jpg">

<img src="Pictures/TriangulationCoord.jpg">

In [4]:
#Let's try this out.  These are bands about each pair connected by an edge
WV1 = np.array([0,1,0,0,0,1,1,0,1,1,1,0,1,0,1,0,1,1])

WSvals = [WV1,R1_rot(WV1),R1Inv_rot(WV1),R2_rot(WV1),R2Inv_rot(WV1)]
EdgeVals = [1,7,2,3,5]
GenPos = [[i,True] for i in EdgeVals]
GenNeg = [[i,False] for i in EdgeVals]

#let's cycle through all the generators and have them act on the bands that should be invariant as a check

for i in range(len(EdgeVals)):
    PosTrue = True
    PosNewGen = Generator(WSvals[i],GenPos[i][0],GenPos[i][1])
    for k in range(len(WSvals[i])):
        if not PosNewGen[k] == WSvals[i][k]:
            PosTrue = False
            break
    NegTrue = True
    NegNewGen = Generator(WSvals[i],GenNeg[i][0],GenNeg[i][1])
    for k in range(len(WSvals[i])):
        if not NegNewGen[k] == WSvals[i][k]:
            NegTrue = False
            break       
    print(EdgeVals[i], WSvals[i], PosTrue, NegTrue)
    
    if not PosTrue:
        print('\n')
        print(WSvals[i])
        print(PosNewGen)
        break

print("\n")

for i in range(len(WSvals)):
    print(EdgeVals[i], WSvals[i],'\n',Generator(Generator(WSvals[i],GenPos[(i+1)%5][0],GenPos[(i+1)%5][1] ),GenNeg[(i+1)%5][0],GenNeg[(i+1)%5][1]),'\n')
#now let's check them against bands that should actually change, and impliment the inverse

1 [0 1 0 0 0 1 1 0 1 1 1 0 1 0 1 0 1 1] True True
7 [1 1 0 1 1 0 0 0 0 1 1 0 1 0 1 0 1 1] True True
2 [1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 1] True True
3 [0 1 0 1 0 0 0 1 1 0 1 1 1 1 0 1 0 1] True True
5 [0 0 0 1 0 1 1 1 0 1 0 1 0 1 1 1 1 0] True True


1 [0 1 0 0 0 1 1 0 1 1 1 0 1 0 1 0 1 1] 
 [0 1 0 0 0 1 1 0 1 1 1 0 1 0 1 0 1 1] 

7 [1 1 0 1 1 0 0 0 0 1 1 0 1 0 1 0 1 1] 
 [1 1 0 1 1 0 0 0 0 1 1 0 1 0 1 0 1 1] 

2 [1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 1] 
 [1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 1] 

3 [0 1 0 1 0 0 0 1 1 0 1 1 1 1 0 1 0 1] 
 [0 1 0 1 0 0 0 1 1 0 1 1 1 1 0 1 0 1] 

5 [0 0 0 1 0 1 1 1 0 1 0 1 0 1 1 1 1 0] 
 [0 0 0 1 0 1 1 1 0 1 0 1 0 1 1 1 1 0] 



In [5]:
print(Lattice_Braid_Operator(WV1,G[0]))
print(Lattice_Braid_Action(WV1,[G[0],G[17],G[30]]))

[0 1 0 0 0 1 1 0 1 1 1 0 1 0 1 0 1 1]
[1 1 2 3 1 2 2 2 2 1 3 2 3 0 3 4 3 3]


<img src="Pictures/TriangulationCoord.jpg">

All of these checks work, and the functions appear to be doing what they are designed to do.  Now we would like to find the exponential stretching rate for general braids.

## Getting the Topological Entropy

In [6]:
get_ipython().magic('matplotlib inline')
import matplotlib.pyplot as plt
import math
from scipy.optimize import curve_fit

#Let's automate this.  Creating a function that will output the braiding entropy and fit
def linear_func(x, a, b):
    return a*x+b

def GetTE(Bin):
    WS = np.array([0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0])
    Length = []
    Iterations = []
    Length.append(Weight_Total(WS))
    Iterations.append(0)
    numiter = 100
    for i in range(numiter):
        WS = Lattice_Braid_Action(WS,Bin)
        Length.append(Weight_Total(WS))
        Iterations.append(Iterations[-1]+len(Bin))

    LWeights = [np.log(Length[i]) for i in range(0,len(Length))]
    indend = len(Length)-1
    fracstart = 2
    indst = int(indend/fracstart)
    popt, pcov = curve_fit(linear_func, Iterations[indst:indend], LWeights[indst:indend])  #fitting to a linear function ax+b
    #popt has the optimal fits for a and b (in that order), and pcov has the covariance
    perr = np.sqrt(np.diag(pcov))  #the one standard deviation errors
    return [popt[0], perr[0]]

#This one is better
def GetTE2(Bin, tolerance = 1e-10, numitermax = 100,Verbose = False):
    WS = np.array([0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0])
    NumGen = len(Bin)
    numitermin = 6
    for i in range(numitermin):
        WS = Lattice_Braid_Action(WS,Bin)
    LogWeight = np.log(Weight_Total(WS))    
    LogWeightPrev = 0
    
    iternum = numitermin
    TE = (LogWeight - LogWeightPrev)/NumGen
    TEprev = 0
    
    while np.abs(TE - TEprev) > tolerance and iternum < numitermax:
        iternum += 1
        WS = Lattice_Braid_Action(WS,Bin)
        LogWeightPrev = LogWeight
        TEprev = TE
        #print(Weight_Total(WS))
        LogWeight = np.log(Weight_Total(WS))
        TE = (LogWeight - LogWeightPrev)/NumGen

    if Verbose:
        if iternum == numitermax:
            print("Braiding Entropy of ", TE, " with tolerance of ", np.abs(TE - TEprev), " after the maximum of ", iternum, " iterations")
        else:
            print("Braiding Entropy of ", TE, " with tolerance of ", np.abs(TE - TEprev), " after ", iternum, " iterations")
    return [TE, np.abs(TE - TEprev)]

In [7]:
print(GetTE([G[2],G[21],G[35]]))
print(GetTE2([G[3],G[30],G[20]],numitermax = 8,Verbose = True))

[0.6638262970065286, 7.521188940913246e-17]
Braiding Entropy of  0.7038029032968621  with tolerance of  2.647843157732588e-06  after the maximum of  8  iterations
[0.7038029032968621, 2.647843157732588e-06]


## Checking braid words by brute force
Here we will run through the combinatorial possibilities for braid words

In [33]:
#G1: 1,3,5
g1vals = [1,3,5]
G1 = getGroup(g1vals)
#G2:
g2vals = [7,8,9]
G2 = getGroup(g2vals)
#G3:
g3vals = [2,4,6]
G3 = getGroup(g3vals)
#these three groups go together (they don't share any edges), so we package them together
Gset1 = G1+G2+G3
#G4:
g4vals = [2,5,9]
G4 = getGroup(g4vals)
#G5:
g5vals = [1,4,8]
G5 = getGroup(g5vals)
#G6:
g6vals = [3,6,7]
G6 = getGroup(g6vals)
#these three groups also go together (they don't share any edges), so we package them together too
Gset2 = G4+G5+G6
#now for the full combined set:
G = Gset1+Gset2

Gstart = G1+G4

GN1 = G2+G3
GN2 = G1+G3
GN3 = G1+G2
GN4 = G5+G6
GN5 = G4+G6
GN6 = G4+G5

GN = [GN1,GN2,GN3,GN4,GN5,GN6]

gvalsdict = {"135":0,"789":1,"246":2,"259":3,"148":4,"367":5}

def GetIndex(BopIn):
    keyid = str(BopIn[0][0])+str(BopIn[1][0])+str(BopIn[2][0])
    return gvalsdict[keyid]

<img src="Pictures/OpTemplates2.jpg">

In [29]:
#here we make a recursive function that will do the same thing at the above nested loops, but out to an arbitrary depth.
import time

def GetTEPObraids(depth_end = 8, BraidIn  = [], AccumBraids = [[0,None]]):
    if len(BraidIn) < depth_end:
        if len(BraidIn) == 0:
            for i in range(len(Gstart)):
                BraidOut = BraidIn + [Gstart[i]]
                AccumBraids = GetTEPObraids(depth_end,BraidOut,AccumBraids)
        else:
            #add endings to the current braid and pass through this function
            for i in range(len(G)):
                BraidOut = BraidIn + [G[i]]
                AccumBraids = GetTEPObraids(depth_end,BraidOut,AccumBraids)

    else:
        #halting condition
        #find the topological entropy for this braid
        #return the accumulated braid list with the new braid if it has 
        latestMaxTE = AccumBraids[-1][0]
        TEtemp = GetTE2(BraidIn,numitermax = 10)[0]

        if TEtemp >= (latestMaxTE-0.0001):
            if TEtemp <= (latestMaxTE+0.0001):
                AccumBraids.append([TEtemp,BraidIn])
            else:
                AccumBraids = [[TEtemp,BraidIn]]
    return AccumBraids
    

In [32]:
def CounterToStr(countin):
    if countin < 10:
        return "000" + str(countin)
    elif countin < 100:
        return "00" + str(countin)
    elif countin < 1000:
        return "0" + str(countin)
    elif countin < 10000:
        return str(countin)
    else:
        return "countertoobig"

In [ ]:
timelimit = 60*60*10  #10 hours (in seconds)
#timelimit = 60*2
base = "Hex6ptmaxTEPObraidsofLen"
ending = ".txt"

braidlen = 2
timeout = False
while not timeout:

    filename = base + CounterToStr(braidlen) + ending
    fileOut = open(filename,"w")
    fileOut.write("Max TEPO Braids and TEPO value for braids of length "+str(braidlen)+": \n")
    timestart = time.time()
    AB = GetTEPObraids(braidlen)
    timeend = time.time()
    for i in range(len(AB)):
        fileOut.write(str(AB[i][0])+" "+str(AB[i][1])+"\n")
    fileOut.close()

    braidlen += 1
    if abs(timeend-timestart)*len(G) > timelimit:
        timeout  = True


In [ ]:
def GetTEPObraids2(depth_end = 8, BraidIn  = [], AccumBraids = [[0,None]]):

    if len(BraidIn) < depth_end:
        if len(BraidIn) == 0:
            for i in range(len(Gstart)):
                BraidOut = BraidIn + [Gstart[i]]
                AccumBraids = GetTEPObraids2(depth_end,BraidOut,AccumBraids)
        else:
            #add endings to the current braid and pass through this function
            indlast = GetIndex(BraidIn[-1])
            for i in range(len(GN[indlast])):
                BraidOut = BraidIn + [GN[indlast][i]]
                AccumBraids = GetTEPObraids2(depth_end,BraidOut,AccumBraids)
    else:
        #halting condition
        #find the topological entropy for this braid
        #return the accumulated braid list with the new braid if it has 
        latestMaxTE = AccumBraids[-1][0]
        TEtemp = GetTE2(BraidIn,numitermax = 10)[0]

        if TEtemp >= (latestMaxTE-0.0001):
            if TEtemp <= (latestMaxTE+0.0001):
                AccumBraids.append([TEtemp,BraidIn])
            else:
                AccumBraids = [[TEtemp,BraidIn]]
    return AccumBraids

In [ ]:
timelimit = 60*60*10  #10 hours (in seconds)
base = "Hex6ptmaxTEPObraidsofLen"
ending = "targeted.txt"


timeout = False

while not timeout:

    filename = base + CounterToStr(braidlen) + ending
    fileOut = open(filename,"w")
    fileOut.write("Max TEPO Braids and TEPO value for braids of length "+str(braidlen)+": \n")
    fileOut.write("Targeted Search \n")
    timestart = time.time()
    AB = GetTEPObraids2(braidlen)
    timeend = time.time()
    for i in range(len(AB)):
        fileOut.write(str(AB[i][0])+" "+str(AB[i][1])+"\n")
    fileOut.close()

    braidlen += 1
    if abs(timeend-timestart)*len(GN[0]) > timelimit:
        timeout  = True
print(braidlen)